# Copyright (c) 2026
"""Public facade for bounded lexical analysis and content indexing."""

from devtools.context.retrieval.lexical.analysis import (
    RepositoryTextLexicalCollectionAnalysis,
    RepositoryTextLexicalDocumentAnalysis,
    RepositoryTextLexicalObservation,
    analyze_repository_text_document,
    analyze_repository_text_document_collection,
    iter_lexical_spans,
)
from devtools.context.retrieval.lexical.bm25 import (
    RepositoryTextLexicalBm25Match,
    RepositoryTextLexicalBm25RetrievalResult,
    RepositoryTextLexicalBm25Settings,
    RepositoryTextLexicalBm25TermContribution,
    RepositoryTextLexicalQuery,
    RepositoryTextLexicalQueryObservation,
    analyze_repository_text_lexical_query,
    retrieve_repository_text_documents_by_bm25,
    retrieve_repository_text_documents_by_content_bm25,
)
from devtools.context.retrieval.lexical.evaluation import (
    RepositoryTextLexicalRetrievalEvaluationCase,
    RepositoryTextLexicalRetrievalEvaluationResult,
    RepositoryTextLexicalRetrievalEvaluationSummary,
    RepositoryTextLexicalRetrievedRelevantResource,
    evaluate_repository_text_lexical_bm25_retrieval,
    summarize_repository_text_lexical_retrieval_evaluations,
)
from devtools.context.retrieval.lexical.filename import (
    RepositoryTextFilenameLexicalBm25TermContribution,
    RepositoryTextFilenameLexicalDocumentAnalysis,
    RepositoryTextFilenameLexicalDocumentFrequency,
    RepositoryTextFilenameLexicalDocumentStatistics,
    RepositoryTextFilenameLexicalIndex,
    RepositoryTextFilenameLexicalPosting,
    RepositoryTextFilenameLexicalTermFrequency,
    RepositoryTextFilenameLexicalTermPostings,
    build_repository_text_filename_lexical_index,
)
from devtools.context.retrieval.lexical.index import (
    RepositoryTextLexicalInvertedIndex,
    RepositoryTextLexicalPosting,
    RepositoryTextLexicalTermPostings,
    build_repository_text_lexical_inverted_index,
)
from devtools.context.retrieval.lexical.statistics import (
    RepositoryTextLexicalCorpusStatistics,
    RepositoryTextLexicalDocumentFrequency,
    RepositoryTextLexicalDocumentStatistics,
    RepositoryTextLexicalTermFrequency,
    calculate_repository_text_lexical_corpus_statistics,
)

__all__ = [
    "RepositoryTextFilenameLexicalBm25TermContribution",
    "RepositoryTextFilenameLexicalDocumentAnalysis",
    "RepositoryTextFilenameLexicalDocumentFrequency",
    "RepositoryTextFilenameLexicalDocumentStatistics",
    "RepositoryTextFilenameLexicalIndex",
    "RepositoryTextFilenameLexicalPosting",
    "RepositoryTextFilenameLexicalTermFrequency",
    "RepositoryTextFilenameLexicalTermPostings",
    "RepositoryTextLexicalBm25Match",
    "RepositoryTextLexicalBm25RetrievalResult",
    "RepositoryTextLexicalBm25Settings",
    "RepositoryTextLexicalBm25TermContribution",
    "RepositoryTextLexicalCollectionAnalysis",
    "RepositoryTextLexicalCorpusStatistics",
    "RepositoryTextLexicalDocumentAnalysis",
    "RepositoryTextLexicalDocumentFrequency",
    "RepositoryTextLexicalDocumentStatistics",
    "RepositoryTextLexicalInvertedIndex",
    "RepositoryTextLexicalObservation",
    "RepositoryTextLexicalPosting",
    "RepositoryTextLexicalQuery",
    "RepositoryTextLexicalQueryObservation",
    "RepositoryTextLexicalRetrievalEvaluationCase",
    "RepositoryTextLexicalRetrievalEvaluationResult",
    "RepositoryTextLexicalRetrievalEvaluationSummary",
    "RepositoryTextLexicalRetrievedRelevantResource",
    "RepositoryTextLexicalTermFrequency",
    "RepositoryTextLexicalTermPostings",
    "analyze_repository_text_document",
    "analyze_repository_text_document_collection",
    "analyze_repository_text_lexical_query",
    "build_repository_text_filename_lexical_index",
    "build_repository_text_lexical_inverted_index",
    "calculate_repository_text_lexical_corpus_statistics",
    "evaluate_repository_text_lexical_bm25_retrieval",
    "iter_lexical_spans",
    "retrieve_repository_text_documents_by_bm25",
    "retrieve_repository_text_documents_by_content_bm25",
    "summarize_repository_text_lexical_retrieval_evaluations",
]
